apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: projet-final
  labels:
    app: backend
    tier: backend
    project: projet-final
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
